#cloud-config
groups:
  - docker
apt_update: true
apt_upgrade: true
packages:
  - nginx
  - docker-compose
write_files:
  - owner: root:root
    path: /home/ubuntu/cloud-init-status.sh
    content: |
      #!/usr/bin
      FOUND=0
      FILE=/var/lib/cloud/instance/boot-finished
      echo -e "\n";
      while [ $FOUND -eq "0" ]
      do
        if [ -f $FILE ]
          then FOUND=1;
        else
          sleep 4s; echo -ne "\033[1;33m# \033[0m";
        fi
      done
  - owner: root:root
    path: /etc/nginx/sites-available/zse
    content: |
      server {
        listen 80;
        server_name api.stonks.co.zw;
        location / {
          proxy_pass http://localhost:8000;
        }
      }
      server {
        listen 80;
        server_name stonks.co.zw www.stonks.co.zw;
        location / {
          proxy_pass http://localhost:5000;
        }
      }      
runcmd:
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - apt-get update
  - apt-get install docker-ce -y
  # - usermod -aG docker ubuntu
  # - su - ubuntu
  - ufw allow proto tcp from any to any port 80
  - ufw allow OpenSSH
  - ufw enable
  - sudo su
  - cd /var/www/ && git clone https://github.com/spaghettiwews/zse-api.git
  - docker run -d -p 8000:8000 -v /var/www/zse-api/data:/app/data whiskeymikey/zse-api:latest
  - docker run -d -p 5000:80 whiskeymikey/zse-web:latest
  - ln -fs /etc/nginx/sites-available/zse /etc/nginx/sites-enabled/default
  - systemctl restart nginx